# Generated by Django 3.1.2 on 2021-03-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210316_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='body',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
