# Generated by Django 3.1.2 on 2021-04-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_file',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(default='www.noimage.com'),
        ),
    ]
