# Generated by Django 3.1.2 on 2021-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210416_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_file',
            field=models.ImageField(default='default.jpg', max_length=500, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(default='www.noimage.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
