# Generated by Django 3.1.2 on 2021-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210417_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_file',
            field=models.ImageField(default='default.jpg', max_length=700, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(default='www.noimage.com', max_length=700),
        ),
    ]
