# Generated by Django 3.1.2 on 2021-05-04 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20210417_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='similar_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
