# Generated by Django 3.1.2 on 2021-07-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
