# Generated by Django 3.1.2 on 2021-07-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wikipedia_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('entity', models.ManyToManyField(to='properties.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='articles',
            field=models.ManyToManyField(through='properties.Sentiment', to='properties.Property'),
        ),
    ]
