# Generated by Django 3.1.2 on 2021-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20210718_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('PERSON', 'Person'), ('GPE', 'Geopolitical Entity'), ('ORG', 'Organization'), ('GEO', 'Geographical Entity')], default='PERSON', max_length=10),
        ),
    ]
