# Generated by Django 3.1.2 on 2021-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20210719_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
