# Generated by Django 3.1.2 on 2021-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20210719_1820'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sentiment',
            constraint=models.UniqueConstraint(fields=('article', 'entity'), name='only_one_result_for_article -entity'),
        ),
    ]
