# Generated by Django 3.1.2 on 2021-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20210719_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipedia_url',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
