# Generated by Django 3.1.2 on 2021-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20210719_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='article_ids',
        ),
        migrations.AddField(
            model_name='library',
            name='article_ids',
            field=models.ManyToManyField(to='properties.Property'),
        ),
    ]
