# Generated by Django 3.1.2 on 2021-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='body',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(default='www.noimage.com', max_length=1000),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
