# Generated by Django 3.1.2 on 2021-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20210821_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='source',
            field=models.CharField(default='', max_length=50),
        ),
    ]
